### ISSUE TITLE
rfmcall installation error : No valid versions available for rfmcall  

### ISSUE THREAD

**Issue by h2plucifer** [SAP/fundamental-tools#7]
Hi ,

Need to check if I can get information regarding the **rfmcall** installation error as it seems the module has been unpublished (link : https://developer.aliyun.com/mirror/npm/package/rfmcall).

As we had implementation with node-rfc & rfmcall , so need to check if there would be any updated release of rfmcall or it has been permanently unpublished.

Thanks

**Comment by bsrdjan** [comment]
The `rfmcall` is now superseded by `abap call` command of https://www.npmjs.com/package/abap-api-tools

The initial release just published, feedback welcome

**Comment by h2plucifer** [comment]
Thanks @bsrdjan  for the update.

Will check the same & let you know.
